spring:
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${APP_PROFILE}

  jpa:
    open-in-view: false

security:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  jwt:
    duration: ${JWT_DURATION}

cors:
  origins: ${CORS_ORIGINS}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    persist-authorization: true
